{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{template "gradle-cache.fullname" . }}
  labels:
    app: {{ template "gradle-cache.fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{ .Release.Name }}-{{ .Values.name }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
    - port: {{.Values.service.port}}
      name: http
      targetPort: {{.Values.internalPort}}
      {{if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)))}}
      nodePort: {{.Values.service.nodePort}}
      {{end}}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.name }}"
  type: {{.Values.service.type}}
{{- end }}
