{{- if .Values.jenkins.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{- if .Values.jenkins.persistence.Annotations }}
  annotations:
{{ toYaml .Values.jenkins.persistence.Annotations | indent 4 }}
{{- end }}
  name: {{ .Values.jenkins.persistence.existingClaim }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.jenkins.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jenkins.persistence.size | quote }}

{{- if .Values.jenkins.persistence.storageClass }}
{{- if (eq "-" .Values.jenkins.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.jenkins.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
