{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  labels:
    {{- include "og-application.labels" . | nindent 4 }}
spec:
  provider:
    {{- if .Values.clusterSecretStore.provider.aws }}
    aws:
      service: {{ .Values.clusterSecretStore.provider.aws.service | default "SecretsManager" }}
      region: {{ .Values.clusterSecretStore.provider.aws.region | default "us-west-2" }}
      {{- if .Values.clusterSecretStore.provider.aws.auth }}
      auth:
        {{- if .Values.clusterSecretStore.provider.aws.auth.jwt }}
        jwt:
          serviceAccountRef:
            name: {{ .Values.clusterSecretStore.provider.aws.auth.jwt.serviceAccountRef.name }}
            {{- if .Values.clusterSecretStore.provider.aws.auth.jwt.serviceAccountRef.namespace }}
            namespace: {{ .Values.clusterSecretStore.provider.aws.auth.jwt.serviceAccountRef.namespace }}
            {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
