{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "og-application.fullname" . }}
  labels:
    {{- include "og-application.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "og-application.fullname" . }}-secrets
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
    {{- with .Values.externalSecret.target.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.externalSecret.secrets }}
  data:
    {{- range $secretKey, $value := .Values.externalSecret.secrets }}
    {{- $ref := splitList "::" (toString $value) }}
    {{- $remoteKey := index $ref 0 }}
    {{- $remoteProperty := $secretKey }}
    {{- if gt (len $ref) 1 }}
    {{- $remoteProperty = index $ref 1 }}
    {{- end }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $remoteKey }}
        property: {{ $remoteProperty }}
    {{- end }}
  {{- end }}
{{- end }}
