{{- if .Values.httproute.enabled -}}
{{- $fullName := include "og-application.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.httproute.namespace | default .Release.Namespace }}
  labels:
    {{- include "og-application.labels" . | nindent 4 }}
  {{- with .Values.httproute.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    {{- include "og-application.annotations" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.httproute.rules }}
    - {{- if .matches }}
      matches:
        {{- toYaml .matches | nindent 8 }}
      {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        {{- if .backendRefs }}
        {{- toYaml .backendRefs | nindent 8 }}
        {{- else }}
        - name: {{ .serviceName | default $fullName }}
          namespace: {{ .serviceNamespace | default $.Release.Namespace }}
          port: {{ .servicePort | default $svcPort }}
          {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
        {{- end }}
      {{- if .timeouts }}
      timeouts:
        {{- toYaml .timeouts | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
