{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name | default (printf "%s-secret-store" (include "og-application.fullname" .)) }}
  labels:
    {{- include "og-application.labels" . | nindent 4 }}
spec:
  provider:
    {{- if .Values.secretStore.provider.aws }}
    aws:
      service: {{ .Values.secretStore.provider.aws.service | default "SecretsManager" }}
      region: {{ .Values.secretStore.provider.aws.region | default "us-west-2" }}
      {{- if .Values.secretStore.provider.aws.auth }}
      auth:
        {{- if .Values.secretStore.provider.aws.auth.jwt }}
        jwt:
          serviceAccountRef:
            name: {{ .Values.secretStore.provider.aws.auth.jwt.serviceAccountRef.name | default (include "og-application.serviceAccountName" .) }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
