{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-core.serviceAccountName" . }}-config
  labels:
    {{- include "application-core.labels" . | nindent 4 }}
  annotations:
    {{- include "application-core.annotations" $ | nindent 4 }}
data:
  {{- range $key, $value := $.Values.configMap.data }}
  {{ $key }}: {{ toYaml $value }}
  {{- end }}
{{- end }}
