{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application-core.fullname" . }}
  labels:
    {{- include "application-core.labels" . | nindent 4 }}
  annotations:
    {{- include "application-core.annotations" $ | nindent 4 }}
spec:
  data:
  {{- if .Values.externalSecret.data }}
  {{- range .Values.externalSecret.data}}
    - remoteRef:
        conversionStrategy: {{ .remoteRef.conversionStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
      secretKey: {{ .secretKey }}
  {{- end }}
  {{- end }}
  {{- if .Values.externalSecret.simple }}
  {{- range .Values.externalSecret.simple }}
  {{- $key := .key -}}
  {{- range .property }}
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ $key }}
        property: {{ . }}
      secretKey: {{ . }}
  {{- end }}
  {{- end }}
  {{- end }}
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
    name: {{ include "application-core.fullname" . }}-config
    template:
      engineVersion: v2
      data:
      {{- if .Values.externalSecret.simple }}
      {{- range .Values.externalSecret.simple }}
      {{- range .property }}
        {{ . }}: {{`"{{ .`}}{{.}}{{` | toString }}"`}}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if $.Values.externalSecret.target.template.data }}
      {{- range $key, $value := $.Values.externalSecret.target.template.data }}
        {{ $key }}: {{ toYaml $value }}
      {{- end }}
      {{- end }}
{{- end }}
