{{- if .Values.rollouts.successRateTemplate.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-core.fullname" . }}-preview
  labels:
    {{- include "application-core.labels" . | nindent 4 }}
  annotations:
    {{- include "application-core.annotations" $ | nindent 4 }}
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {}
{{- end -}}